USE [master]
GO

/****** Object:  Database [schooldb]    Script Date: 01/11/2024 23:34:32 ******/
CREATE DATABASE [schooldb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'schooldb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\schooldb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'schooldb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\schooldb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [schooldb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [schooldb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [schooldb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [schooldb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [schooldb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [schooldb] SET ARITHABORT OFF 
GO

ALTER DATABASE [schooldb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [schooldb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [schooldb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [schooldb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [schooldb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [schooldb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [schooldb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [schooldb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [schooldb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [schooldb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [schooldb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [schooldb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [schooldb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [schooldb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [schooldb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [schooldb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [schooldb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [schooldb] SET RECOVERY FULL 
GO

ALTER DATABASE [schooldb] SET  MULTI_USER 
GO

ALTER DATABASE [schooldb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [schooldb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [schooldb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [schooldb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [schooldb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [schooldb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [schooldb] SET QUERY_STORE = ON
GO

ALTER DATABASE [schooldb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [schooldb] SET  READ_WRITE 
GO

